---
swagger: "2.0"
info:
  description: "API para criação e listagem de PDVs"
  version: "1.0.0"
  title: "Zx Ventures PDVs"
  contact:
    email: "rodrigoalviani@gmail.com"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "pdv"
  description: "Criação, listagem e detalhes do PDV"
schemes:
- "http"
paths:
  /pdv:
    get:
      tags:
      - "pdv"
      summary: "Busca de PDVs por geolocalização"
      description: ""
      operationId: "getPdv"
      produces:
      - "application/json"
      parameters:
      - name: "ll"
        in: "query"
        description: "Long/Lat atual"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/PDV"
        400:
          description: "ll is required"
      x-swagger-router-controller: "Pdv"
    post:
      tags:
      - "pdv"
      summary: "Criar PDV"
      description: ""
      operationId: "addPdv"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto esperado"
        required: true
        schema:
          $ref: "#/definitions/PDV"
      responses:
        201:
          description: "created"
        400:
          description: "all fields are required/duplicate key"
      x-swagger-router-controller: "Pdv"
  /pdv/{id}:
    get:
      tags:
      - "pdv"
      summary: "Retorna o PDV por ID"
      description: ""
      operationId: "getPdvById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do PDV"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/PDV"
        400:
          description: "id is required"
        404:
          description: "pdv not found"
      x-swagger-router-controller: "Pdv"
definitions:
  PDV:
    type: "object"
    required:
    - "address"
    - "coverageArea"
    - "document"
    - "id"
    - "ownerName"
    - "tradingName"
    properties:
      id:
        type: "integer"
        format: "int64"
      tradingName:
        type: "string"
        example: "Bar do Jão"
      ownerName:
        type: "string"
        example: "Jão do Bar"
      document:
        type: "string"
        example: "12.345.678/000199"
      address:
        $ref: "#/definitions/PDV_address"
      coverageArea:
        $ref: "#/definitions/PDV_coverageArea"
    example:
      tradingName: "Bar do Jão"
      address:
        coordinates: "[12.123, 21.321]"
      ownerName: "Jão do Bar"
      document: "12.345.678/000199"
      id: 0
      coverageArea:
        coordinates: "[[[[12.123, 21.321], [12.124, 21.320]]]]"
  PDV_address:
    properties:
      coordinates:
        type: "array"
        example: "[12.123, 21.321]"
        items:
          type: "number"
    example:
      coordinates: "[12.123, 21.321]"
  PDV_coverageArea:
    properties:
      coordinates:
        type: "array"
        example: "[[[[12.123, 21.321], [12.124, 21.320]]]]"
        items:
          type: "number"
    example:
      coordinates: "[[[[12.123, 21.321], [12.124, 21.320]]]]"
